### ISSUE TITLE
How do you branch to an unnamed block for traversing up one or more blocks?

### ISSUE THREAD

**Issue by AjaniBilby** [AssemblyScript/binaryen.js#83]
In standard WAT format you can go up one block by simply providing a number for how many blocks you want to traverse up
```wat
(block
  (loop $continue
    ;; do stuff
    br_if $cond 1
    br 0
  )
)
```

However when using binaryen the type information on the `br_if` and `br` functions require a `string` for the label.
And if I try to force a number in as the first argument I get some kind of error - however because the binaryen library is minified the error log instantly blows out my CLI history so I can read the actual error message, instead my entire terminal history is filled with a single line reference.

Being able to traverse up blocks by number instead of label name would make compilation in a recursive style much easier, but instead due to this limitation of requiring the use of string labels to jump to any point I will need to keep track of the name of the block above me at any single point in time while my compiler is going into deeper and deeper levels of nested behaviour.

**Comment by CountBleck** [comment]
The [relevant bindings](https://github.com/WebAssembly/binaryen/blob/aaf1dac4/src/js/binaryen.js-post.js#L682-L687) just wrap the C API, so this would be a Binaryen issue if it's an issue at all.

I'd just associate each block with a numeric ID from an incrementing counter, keep a stack of those IDs in your context, and use those for labels. It might not be a good solution, but it's *a* solution.

Sidenote: *maybe* the [Relooper](https://github.com/AssemblyScript/binaryen.js#relooper) interface binaryen.js exposes *could perhaps* be useful to you...I can't say for sure.

Another sidenote: I think you can just do `br_if $not_cond 0` instead of those two `br` and `br_if` instructions, which might be more convenient when compiling C-style `for` and `while` loops, since the condition there is for continuing the loop (and not for breaking) and inverting the condition wouldn't be necessary. I think.
